services:
  web-server:
    build: web-server
    ports:
      - 9001:80
    restart: unless-stopped

  signaling-server:
    build: signaling-server
    ports:
      - 8001:8001
    restart: unless-stopped
